= English-Interlingue Dictionary
:author: Marcos Cruz (programandala.net)
:revdate: 2020-12-04
:toc:
:toc-levels: 2
:toc-title: Contents/Contenete/Enhavo

// This file is part of the project
// _English-Interlingue Dictionary_
// (http://ne.alinome.net)
//
// By Marcos Cruz (programandala.net)

:user: ~

// English {{{1
== English

// About this project {{{2
=== About this project

Goal:: Create an EPUB e-book and a DICT format dictionary, among other
standard formats, from the digitalized contents of the
_English-Interlingue Dictionary_ by Charles Kemp and F.R. Pope, 1958.

Author:: Marcos Cruz (programandala.net), 2019

Website:: http://ne.alinome.net[ne.alinome.net]

Note: On 2020-12-04 the Git repository was converted to
http://fossil-scm.rog[Fossil]. GitHub is used only as a copy.

// How to build the dictionary {{{2
=== How to build the dictionary

If you cannot wait the release of the next version, you can build the
dictionary files yourself.

First, make sure the programs listed under the "Requirements" section
of the <Makefile> file are installed in your system.

Then enter the project's directory and give the `make` command as
follows:

|===
| Command             | Effect

| make                | Build all documents
| make adoc           | Build the Asciidoctor document
| make dbk            | Build the DocBook document
| make dict           | Build the DICT format
| make epub           | Build the EPUB documents
| make epuba          | Build an EPUB document with Asciidoctor EPUB3
| make epubd          | Build an EPUB document with dbtoepub
| make epubp          | Build an EPUB document with pandoc
| make epubx          | Build an EPUB document with xsltproc
| make odt            | Build an OpenDocument document 
| make pdf            | Build the PDF documents (both sizes)
| make pdfa4          | Build a PDF document (DIN A4 size)
| make pdfl           | Build a PDF document (letter size)
| sudo make install   | Install the DICT files
| sudo make uninstall | Uninstall the DICT files
|===

The documents are built in the <target> directory.

// DICT command (for GNU/Linux systems) {{{2
=== DICT command (for GNU/Linux systems)


The file <src/interlingue.sh> is a simple shell wrapper for DICT.  You
can copy or link it to a location in your path, e.g. as <{user}/bin/>,
<{user}/.local/bin/> or </usr/local/bin/>, for example with name `ie`.
Then the command `ie` will search all installed dictonaries that have
the word "interlingue" (case insensitive) in their description.

// Interlingue {{{1
== Interlingue

// Pri ti projecte {{{2
=== Pri ti projecte

Scope:: Crear un EPUB-libre e un DICT-formati dictionarium, inter
altri formates standard, ex li digitalisat contenete de
_English-Interlingue Dictionary_ (Dictionarium Anglesi-Interlingue) de
Charles Kemp e F.R. Pope, 1958.

Autor:: Marcos Cruz (programandala.net), 2019

Loc web:: http://ne.alinome.net[ne.alinome.net]

Note: In 2020-12-04 li depositoria de Git esset convertet a
http://fossil-scm.org[Fossil]. GitHub es usat solmen quam un copie.

// Qualmen constructer li dictionarium {{{2
=== Qualmen constructer li dictionarium

Si vu ne posse atender li liberation de li sequent version, vu self
posse constructer li dictionarium-documentes.

In prim, ples confirmar que li programes listat in li section
"Requirements" (besones) del document <Makefile> es installat in vor
sistema.

Tande ples intrar li documentiere del projecte e comandar `make` secun
ti exemples:

|===
| Comande             | Efecte

| make                | Constructer omni documentes
| make adoc           | Constructer li document Asciidoctor
| make dbk            | Constructer li document DocBook
| make dict           | Constructer li document DICT
| make epub           | Constructer li document EPUB (omni variantes)
| make epuba          | Constructer li document EPUB per Asciidoctor EPUB3
| make epubd          | Constructer li document EPUB per dbtoepub
| make epubp          | Constructer li document EPUB per pandoc
| make epubx          | Constructer li document EPUB per xsltproc
| make odt            | Constructer li document OpenDocument
| make pdf            | Constructer li document PDF (ambi grandores)
| make pdfa4          | Constructer li document PDF (grandore DIN A4)
| make pdfl           | Constructer li document PDF (grandore "letter")
| sudo make install   | Instalar li documentes DICT
| sudo make uninstall | Desinstalar li documentes DICT
|===

Li documentes es creat in li documentiere <target> (scope).

// DICT-comande (por sistemas GNU/Linux) {{{2
=== DICT-comande (por sistemas GNU/Linux)

Li document <src/interlingue.sh> es un comande por simplificar li
consultas de DICT. Tu posse copiar o ligar it ad-in un documentiere in
un ex tui documentieres de programas, por exemple <{user}/bin/>,
<{user}/.local/bin/> or </usr/local/bin/>, fórsan con li curt nómine
`ie`.  Tande li comande `ie` va serchar omni dictionariums instalat
quel have li parol "interlingue" in lor descrition (índiferent per
majuscules o minuscules).

// Esperanto {{{1
== Esperanto

// Pri ĉi projekto {{{2
=== Pri ĉi projekto

Celo:: Krei  EPUB-an bitlibron kaj DICT-formatan vortaron, inter aliaj
normaj formatoj, el la bitigita enhavo de _English-Interlingue
Dictionary_ (Angla-Interlingvea Vortaro) de Charles Kemp kaj F.R. Pope,
1958.

Aŭtoro:: Marcos Cruz (programandala.net), 2019

Retpaĝaro:: http://ne.alinome.net[ne.alinome.net]

Noto: Je 2020-12-04 la Git-deponejo estis konvertita al
http://fossil-scm.org[Fossil]. GitHub estas uzata nur kiel kopio.

// Kiel konstrui la vortaron {{{2
=== Kiel konstrui la vortaron

Se vi ne povas atendi la publikigon de la venonta versio, vi mem povas
konstrui la vortar-dosierojn.

Unue, certiĝu ke la programoj enlistigitaj en la fako "Requirements"
(necesaĵoj) de la dosiero <Makefile> estas instalitaj en via sistemo.

Poste eniru la dosierujon de la projekto kaj uzu la ordonon `make`
jene:

|===
| Ordono              | Efiko

| make                | Konstrui ĉiujn dokumentojn
| make dict           | Konstrui la dokumenton DICT
| make dbk            | Konstrui la dokumenton DocBook
| make epub           | Konstrui la dokumenton EPUB (ĉiujn variantojn)
| make epuba          | Konstrui la dokumenton EPUB per Asciidoctor EPUB3
| make epubd          | Konstrui la dokumenton EPUB per dbtoepub
| make epubp          | Konstrui la dokumenton EPUB per pandoc
| make epubx          | Konstrui la dokumenton EPUB per xsltproc
| make pdf            | Konstrui la dokumenton PDF (ambaŭ grandojn)
| make pdfa4          | Konstrui la dokumenton PDF (grando DIN A4)
| make pdfl           | Konstrui la dokumenton PDF (grando "letter")
| sudo make install   | Instali la DICT-dosierojn
| sudo make uninstall | Malinstali the DICT-dosierojn
|===

La dosieroj estos kreitaj en la dosierujo <target> (celo).

// DICT-ordono (por sistemoj GNU/Linux) {{{2
=== DICT-ordono (por sistemoj GNU/Linux)

La dosiero <src/interlingue.sh> estas simplig-ordono por DICT-serĉoj.
Vi povas kopii or ligi ĝin en dosierujon el viaj program-dosierujojn,
ekzemple <{user}/bin/>, <{user}/.local/bin/> aŭ </usr/local/bin/>,
eble kun mallonga nomo `ie`.  Tiel la ordono `ie` serĉos en ĉiuj
instalitaj vortaroj kiuj havas la vorton "interlingue" en sia
priskribo (majuskloj aŭ minuskloj ne gravas).

