= English-Interlingue Dictionary
:author: Marcos Cruz (programandala.net)
:revdate: 2019-03-09
:toc:
:toc-levels: 2
:toc-title: Contents/Contenete/Enhavo

// This file is part of the project
// _English-Interlingue Dictionary_
// (http://ne.alinome.net)
//
// By Marcos Cruz (programandala.net)

:user: ~

== English

=== About this project

Goal:: Create an EPUB e-book and a DICT format dictionary, among other
standard formats, from the digitalized contents of the
_English-Interlingue Dictionary_ by Charles Kemp and F.R. Pope, 1958.

Author:: Marcos Cruz (programandala.net), 2019

Website:: http://ne.alinome.net[ne.alinome.net]

=== How to build the dictionary

If you cannot wait the release of the next version, you can build the
dictionary files yourself.

First, make sure the programs listed under the "Requirements" section
of the <Makefile> file are installed in your system.

Then enter the project's directory and give the `make` command as
follows:

|===
| Command             | Effect

| make                | Build most formats and variants
| make all            | Build most formats and variants
| make adoc           | Build the Asciidoctor format
| make dict           | Build the DICT format
| make epub           | Build the EPUB format (most variants)
| make epubd          | Build the EPUB format with dbtoepub
| make epubp          | Build the EPUB format with pandoc
| make epubx          | Build the EPUB format with xsltproc
| make odt            | Build the OpenDocument format
| make pdf            | Build the PDF format (both sizes)
| make pdfa4          | Build the DIN A4 size PDF format
| make pdfl           | Build the letter size PDF format
| make xml            | Build the DocBook format
| sudo make install   | Install the DICT files
| sudo make uninstall | Uninstall the DICT files
|===

The documents are built in the <target> directory.

=== DICT command (for GNU/Linux systems)


The file <src/interlingue.sh> is a simple shell wrapper for DICT.  You
can copy or link it to a location in your path, e.g. as <{user}/bin/>,
<{user}/.local/bin/> or </usr/local/bin/>, for example with name `ie`.
Then the command `ie` will search all installed dictonaries that have
the word "interlingue" (case insensitive) in their description.

== Interlingue

=== Pri ti projecte

Scope:: Crear un EPUB-libre e un DICT-formati dictionarium, inter
altri formates standard, ex li digitalisat contenete de
_English-Interlingue Dictionary_ (Dictionarium Anglesi-Interlingue) de
Charles Kemp e F.R. Pope, 1958.

Autor:: Marcos Cruz (programandala.net), 2019

Loc web:: http://ne.alinome.net[ne.alinome.net]

=== Qualmen constructer li dictionarium

Si vu ne posse atender li liberation de li sequente version, vu self
posse constructer li dictionarium-documentes.

In prim, ples confirmar que li programes listat in li section
"Requirements" (besones) del document <Makefile> es installat in vor
sistema.

Tande ples intrar li documentiere del projecte e comandar `make` secun
ti exemples:

|===
| Comande             | Efecte

| make                | Constructer max mult formates e variantes
| make all            | Constructer max mult formates e variantes
| make adoc           | Constructer li formate Asciidoctor
| make dict           | Constructer li formate DICT
| make epub           | Constructer li formate EPUB (max mult variantes)
| make epub1d         | Constructer li formate EPUB per dbtoepub
| make epub1p         | Constructer li formate EPUB per pandoc
| make epub1x         | Constructer li formate EPUB per xsltproc
| make odt            | Constructer li formate OpenDocument
| make pdf            | Constructer li formate PDF (ambi grandores)
| make pdfa4          | Constructer li formate PDF ye grandore DIN A4
| make pdfl           | Constructer li formate PDF ye grandore "letter"
| make xml            | Constructer li formate DocBook
| sudo make install   | Instalar li documentes DICT
| sudo make uninstall | Desinstalar li documentes DICT
|===

Li documentes es creat in li documentiere <target> (scope).

=== DICT-comande (por sistemas GNU/Linux)

Li document <src/interlingue.sh> es un comande por simplificar li
consultas de DICT. Tu posse copiar o ligar it ad-in un documentiere in
un ex tui documentieres de programas, por exemple <{user}/bin/>,
<{user}/.local/bin/> or </usr/local/bin/>, fórsan con li curt nómine
`ie`.  Tande li comande `ie` va serchar omni dictionariums instalat
quel have li parol "interlingue" in lor descrition (índiferent per
majuscules o minuscules).

== Esperanto

=== Pri ĉi projekto

Celo:: Krei  EPUB-an bitlibron kaj DICT-formatan vortaron, inter aliaj
normaj formatoj, el la bitigita enhavo de _English-Interlingue
Dictionary_ (Angla-Interlingvea Vortaro) de Charles Kemp kaj F.R. Pope,
1958.

Aŭtoro:: Marcos Cruz (programandala.net), 2019

Retpaĝaro:: http://ne.alinome.net[ne.alinome.net]

=== Kiel konstrui la vortaron

Se vi ne povas atendi la publikigon de la venonta versio, vi mem povas
konstrui la vortar-dosierojn.

Unue, certiĝu ke la programoj enlistigitaj en la fako "Requirements"
(necesaĵoj) de la dosiero <Makefile> estas instalitaj en via sistemo.

Poste eniru la dosierujon de la projekto kaj uzu la ordonon `make`
jene:

|===
| Ordono              | Efiko

| make                | Konstrui plej multajn formatojn kaj variantojn
| make all            | Konstrui plej multajn formatojn kaj variantojn
| make dict           | Konstrui la formaton DICT
| make epub           | Konstrui la formaton EPUB (plej multajn variantojn)
| make epubd          | Konstrui la formaton EPUB per dbtoepub
| make epubp          | Konstrui la formaton EPUB per pandoc
| make epubx          | Konstrui la formaton EPUB per xsltproc
| make pdf            | Konstrui la formaton PDF (ambaŭ grandojn)
| make pdfa4          | Konstrui la formaton PDF je grando DIN A4
| make pdfl           | Konstrui la formaton PDF je grando "letter"
| make xml            | Konstrui la formaton DocBook
| sudo make install   | Instali la DICT-dosierojn
| sudo make uninstall | Malinstali the DICT-dosierojn
|===

La dosieroj estos kreitaj en la dosierujo <target> (celo).

=== DICT-ordono (por sistemoj GNU/Linux)

La dosiero <src/interlingue.sh> estas simplig-ordono por DICT-serĉoj.
Vi povas kopii or ligi ĝin en dosierujon el viaj program-dosierujojn,
ekzemple <{user}/bin/>, <{user}/.local/bin/> aŭ </usr/local/bin/>,
eble kun mallonga nomo `ie`.  Tiel la ordono `ie` serĉos en ĉiuj
instalitaj vortaroj kiuj havas la vorton "interlingue" en sia
priskribo (majuskloj aŭ minuskloj ne gravas).

