= English-Interlingue Dictionary
:authors: Charles Kemp, F.R. Pope
include::../src/VERSION.adoc[]
:description: English-Interlingue Dictionary
ifdef::backend-pdf[]
:doctype: book
:toc: auto
:toclevels: 2
:toc-title: Contents
endif::[]

// This file is part of the project
// _English-Interlingue Dictionary_
// (http://ne.alinome.net)

// Last modified 201903091835

ifeval::["{format}"=="DICT"]
:in_other_formats: also in EPUB, PDF and other formats
:this: this dictionary
:http: http://
:headwords:
endif::[]

ifeval::["{format}"=="e-book"]
:in_other_formats: in DICT, EPUB, PDF and other formats
:this: this book
:http:
:headwords: For the same reason, in the e-book formats, \
a dot is automatically added \
at the start of the headwords.
endif::[]

ifdef::backend-pdf[]
:format: PDF
:in_other_formats: also in DICT, EPUB and other formats
:this: this book
:http:
:headwords: For the same reason, in the e-book formats, \
a dot is automatically added \
at the start of the headwords.
endif::[]

== About {this}

Title:: {doctitle}.

Authors:: {authors}.

Original publisher:: British Interlingue Association, Warndon
(England), 1958.

Transcription of the original contents:: François Comparot et al., c.
2005 (?).  Available in
http://interlingue.narod.ru/[{http}interlingue.narod.ru] and
http://ie-munde.com[{http}ie-munde.com].

Revision and {format} edition:: Marcos Cruz, 2019.  Available in
http://ne.alinome.net[{http}ne.alinome.net] {in_other_formats}.

Main changes in this edition::

- All errors and typos found, including punctuation, layout and
  notation, have been fixed.
- In order to facilitate the searching some entries have been
  splitted, while others have been combined.  {headwords}
- In order to make the contents more legible in any format, and more
  reusable, the tildes in the definitions have been replaced with the
  headwords.
- The notation and the punctuation have been homogenized.

Some changes and improvements are unfinished yet. See the
http://github.com/ne-alinome/english-interlingue-directory/blob/master/TO-DO.adoc[to-do
list in the project repository] for details.

Edition made only by libre programs:: 
http://asciidoctor.org[Asciidoctor],
https://github.com/asciidoctor/asciidoctor-pdf[asciidoctor-pdf],
dbtoepub,
http://debian.org[Debian],
dictfmt,
http://git-scm.com/[Git],
https://www.gnu.org/software/make/[GNU make],
http://pandoc.org[pandoc],
http://http://jonas.nitro.dk/tig[Tig],
http://vim.org[Vim],
http://xmlsoft.org/XSLT/[xsltproc]...

Version of this edition:: {revnumber}.

Contributions:: Corrections and suggestions for next versions are
welcome at http://ne.alinome.net[{http}ne.alinome.net].

// -------------------------------------------------------------
